name = "ParametrisedConvexApproximators"
uuid = "668502ff-1e8f-42bf-95c7-24f1e819f537"
authors = ["JinraeKim <kjl950403@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Convex = "0.14"
Flux = "0.12"
Optim = "1.5"
SCS = "0.8, 0.9"
Transducers = "0.4"
UnPack = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
